services:
  mongo:
    image: mongo:7
    container_name: notif-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: notif-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notif-backend
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./backend:/app
      - /app/node_modules

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notif-worker
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    command: ["npm", "run", "worker:dev"]
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notif-frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
  redis_data:

